services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: food_recommender
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/food_recommender
      - JWT_SECRET_KEY=dev-secret-key-change-in-production
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      # - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      # - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000,https://foodly-hackmit.vercel.app,https://foodly.dag.gy,https://foodly-back.dag.gy
      - ENVIRONMENT=development
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn api_router:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # Required for HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
