
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: food_recommender
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/food_recommender
      - JWT_SECRET_KEY=dev-secret-key-change-in-production
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      # - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      # - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000
      - ENVIRONMENT=development
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn api_router:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
