/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check if the API is running and healthy
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API Information
         * @description Get basic information about the Food Recommender API
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google OAuth Authentication
         * @description Authenticate or register a user using Google OAuth ID token
         */
        post: operations["google_auth_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get information about the currently authenticated user
         */
        get: operations["get_current_user_info_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user_profile/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Taste Profile
         * @description Retrieve a user's complete taste profile including preferences and food history
         */
        get: operations["get_user_profile_user_profile__user_id__get"];
        put?: never;
        /**
         * Update User Taste Profile
         * @description Update a user's taste profile with new preferences and food history
         */
        post: operations["update_user_profile_user_profile__user_id__post"];
        /**
         * Delete User Taste Profile
         * @description Permanently delete a user's taste profile and all associated data
         */
        delete: operations["delete_user_profile_user_profile__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/doordash/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Nearby Restaurants
         * @description Get nearby restaurants from DoorDash API
         */
        post: operations["get_nearby_restaurants_restaurants_doordash_nearby_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/doordash/restaurant/{restaurant_id}/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Restaurant Menu
         * @description Get restaurant menu from DoorDash API
         */
        get: operations["get_restaurant_menu_restaurants_doordash_restaurant__restaurant_id__menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/doordash/restaurant/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Restaurant Details
         * @description Get restaurant details from DoorDash API
         */
        get: operations["get_restaurant_details_restaurants_doordash_restaurant__restaurant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/google_maps/restaurant/{restaurant_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Restaurant Reviews
         * @description Get Google Maps reviews for a restaurant
         */
        get: operations["get_restaurant_reviews_restaurants_google_maps_restaurant__restaurant_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/google_maps/restaurant/{restaurant_id}/item/{item_name}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Menu Item Reviews
         * @description Get reviews mentioning a specific menu item
         */
        get: operations["get_menu_item_reviews_restaurants_google_maps_restaurant__restaurant_id__item__item_name__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/google_maps/restaurant/{restaurant_id}/place_details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Place Details
         * @description Get detailed place information from Google Maps
         */
        get: operations["get_place_details_restaurants_google_maps_restaurant__restaurant_id__place_details_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/beli/restaurant/{restaurant_id}/top_items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Restaurant Top Items
         * @description Get top recommended items at a restaurant from Beli
         */
        get: operations["get_restaurant_top_items_restaurants_beli_restaurant__restaurant_id__top_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/beli/user/{user_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Profile
         * @description Get a user's Beli profile with restaurant reviews
         */
        get: operations["get_user_profile_restaurants_beli_user__user_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Restaurant List
         * @description Get a list of restaurants from in-memory cache
         */
        get: operations["get_restaurants_restaurants__get"];
        put?: never;
        /**
         * Get Nearby Restaurants
         * @description Find restaurants near a specific location using DoorDash data
         */
        post: operations["get_nearby_restaurants_restaurants__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/{restaurant_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Restaurant Data
         * @description Retrieve complete restaurant data including menu items for a specific restaurant
         */
        get: operations["get_restaurant_items_restaurants__restaurant_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recs/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get AI Food Recommendation
         * @description Get a personalized food recommendation using AI analysis of user preferences, restaurant menu, and community data
         */
        post: operations["get_recommendation_recs__restaurant_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recs/{restaurant_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recommendation Context
         * @description Retrieve the data context used for generating recommendations (useful for debugging)
         */
        get: operations["get_recommendation_context_recs__restaurant_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vapi/item-cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get User Cart
         * @description Get Items currently in the user cart for the session.
         */
        post: operations["get_user_cart_vapi_item_cart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vapi/user_cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Item To Cart
         * @description Allow the user to add items to their cart.
         */
        post: operations["add_item_to_cart_vapi_user_cart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vapi/restaurant-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Restaurant Info
         * @description Get full information about restaurant - menu items, reviews, top items, other information
         */
        post: operations["get_restaurant_info_vapi_restaurant_by_id_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vapi/restaurants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Restaurant List
         * @description Fetch restaurants the user has access to order from
         */
        post: operations["get_restaurant_list_vapi_restaurants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BeliRestaurantTopItems */
        BeliRestaurantTopItems: {
            /** Restaurant Id */
            restaurant_id: string;
            /** Restaurant Name */
            restaurant_name: string;
            /** Top Items */
            top_items: components["schemas"]["BeliTopItem"][];
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
        };
        /** BeliTopItem */
        BeliTopItem: {
            /** Name */
            name: string;
            /** Photo Url */
            photo_url?: string | null;
            /** Recommendation Count */
            recommendation_count: number;
        };
        /** BeliUserProfile */
        BeliUserProfile: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /** Restaurant Reviews */
            restaurant_reviews: components["schemas"]["BeliUserRestaurantReview"][];
            /** Total Reviews */
            total_reviews: number;
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
        };
        /** BeliUserRestaurantReview */
        BeliUserRestaurantReview: {
            /** Restaurant Name */
            restaurant_name: string;
            /** Restaurant Id */
            restaurant_id?: string | null;
            /** Rating */
            rating: number;
            /** Notes */
            notes?: string | null;
            /** Date Reviewed */
            date_reviewed?: string | null;
        };
        /** CuisinePreference */
        CuisinePreference: {
            /** Cuisine Type */
            cuisine_type: string;
            /** Preference Level */
            preference_level: number;
        };
        /** DietaryRestriction */
        DietaryRestriction: {
            /** Name */
            name: string;
            /** Severity */
            severity: string;
        };
        /** FlavorProfile */
        FlavorProfile: {
            /** Spicy Tolerance */
            spicy_tolerance: number;
            /** Sweet Preference */
            sweet_preference: number;
            /** Salty Preference */
            salty_preference: number;
            /** Sour Preference */
            sour_preference: number;
            /** Umami Preference */
            umami_preference: number;
            /** Bitter Tolerance */
            bitter_tolerance: number;
        };
        /** FoodItem */
        FoodItem: {
            /** Name */
            name: string;
            /** Restaurant */
            restaurant?: string | null;
            /** Cuisine Type */
            cuisine_type?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** FoodItemRecommendation */
        FoodItemRecommendation: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Price */
            price: number;
            /** Category */
            category: string;
            /** Image Url */
            image_url?: string | null;
            /**
             * Ingredients
             * @default []
             */
            ingredients: string[];
            /**
             * Allergens
             * @default []
             */
            allergens: string[];
            /** Calories */
            calories?: number | null;
            /**
             * Reviews
             * @default []
             */
            reviews: Record<string, never>[];
            /** Reasoning */
            reasoning: string;
        };
        /** GoogleAuthRequest */
        GoogleAuthRequest: {
            /** Id Token */
            id_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
            /**
             * Is New User
             * @default false
             */
            is_new_user: boolean;
        };
        /** MenuItem */
        MenuItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Price */
            price: number;
            /** Category */
            category: string;
            /** Image Url */
            image_url?: string | null;
        };
        /** MenuItemReviews */
        MenuItemReviews: {
            /** Item Name */
            item_name: string;
            /** Restaurant Id */
            restaurant_id: string;
            /** Reviews */
            reviews: components["schemas"]["Review"][];
            /** Average Rating */
            average_rating?: number | null;
            /** Mention Count */
            mention_count: number;
        };
        /** Message */
        Message: {
            /** Toolcalls */
            toolCalls: components["schemas"]["ToolCall"][];
        };
        /** NearbyRestaurantsRequest */
        NearbyRestaurantsRequest: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Radius Miles
             * @default 5
             */
            radius_miles: number | null;
            /**
             * Limit
             * @default 20
             */
            limit: number | null;
        };
        /** NearbyRestaurantsResponse */
        NearbyRestaurantsResponse: {
            /** Restaurants */
            restaurants: components["schemas"]["Restaurant"][];
            /** Total Count */
            total_count: number;
            search_location: components["schemas"]["RestaurantLocation"];
        };
        /** PlaceDetails */
        PlaceDetails: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Formatted Address */
            formatted_address: string;
            /** Formatted Phone Number */
            formatted_phone_number?: string | null;
            /** Website */
            website?: string | null;
            /** Rating */
            rating?: number | null;
            /** User Ratings Total */
            user_ratings_total?: number | null;
            /** Price Level */
            price_level?: number | null;
            /** Opening Hours */
            opening_hours?: string[] | null;
            /**
             * Photos
             * @default []
             */
            photos: string[];
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            /**
             * Curr Dislikes
             * @default []
             */
            curr_dislikes: string[];
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            item: components["schemas"]["FoodItemRecommendation"];
            /** Confidence Score */
            confidence_score: number;
            /** Session Id */
            session_id: string;
            /**
             * Alternatives
             * @default []
             */
            alternatives: components["schemas"]["FoodItemRecommendation"][];
        };
        /** Restaurant */
        Restaurant: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Cuisine Tags
             * @default []
             */
            cuisine_tags: string[];
            address: string;
            /** Rating */
            rating?: number | null;
            /** Price Range */
            price_range: string;
            /** Image Url */
            image_url?: string | null;
        };
        /** RestaurantLocation */
        RestaurantLocation: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Address */
            address: string;
            /** City */
            city: string;
            /** State */
            state: string;
            /** Zip Code */
            zip_code: string;
        };
        /** RestaurantMenu */
        RestaurantMenu: {
            /** Restaurant Id */
            restaurant_id: string;
            /** Restaurant Name */
            restaurant_name: string;
            /** Items */
            items: components["schemas"]["MenuItem"][];
        };
        /** RestaurantReviews */
        RestaurantReviews: {
            /** Restaurant Id */
            restaurant_id: string;
            /** Place Id */
            place_id: string;
            /** Restaurant Name */
            restaurant_name: string;
            /** Overall Rating */
            overall_rating?: number | null;
            /** Total Reviews */
            total_reviews: number;
            /** Reviews */
            reviews: components["schemas"]["Review"][];
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
        };
        /** Review */
        Review: {
            /** Id */
            id: string;
            /** Author Name */
            author_name: string;
            /** Author Url */
            author_url?: string | null;
            /** Language */
            language: string;
            /** Profile Photo Url */
            profile_photo_url?: string | null;
            /** Rating */
            rating: number;
            /** Relative Time Description */
            relative_time_description: string;
            /** Text */
            text: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** TasteProfileResponse */
        TasteProfileResponse: {
            profile: components["schemas"]["UserTasteProfile"];
            /** Recommendations Count */
            recommendations_count: number;
            /** Last Activity */
            last_activity?: string | null;
        };
        /** ToolCall */
        ToolCall: {
            /** Id */
            id: string;
            function: components["schemas"]["ToolCallFunction"];
        };
        /** ToolCallFunction */
        ToolCallFunction: {
            /** Name */
            name: string;
            /** Arguments */
            arguments: string | Record<string, never>;
        };
        /** UpdateTasteProfile */
        UpdateTasteProfile: {
            /** Dietary Restrictions */
            dietary_restrictions?: components["schemas"]["DietaryRestriction"][] | null;
            /** Cuisine Preferences */
            cuisine_preferences?: components["schemas"]["CuisinePreference"][] | null;
            flavor_profile?: components["schemas"]["FlavorProfile"] | null;
            /** Liked Foods */
            liked_foods?: components["schemas"]["FoodItem"][] | null;
            /** Disliked Foods */
            disliked_foods?: components["schemas"]["FoodItem"][] | null;
            /** Favorite Restaurants */
            favorite_restaurants?: string[] | null;
            /** Price Range Preference */
            price_range_preference?: string | null;
            /** Meal Time Preferences */
            meal_time_preferences?: {
                [key: string]: string[];
            } | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Google Id */
            google_id: string;
            /** Profile Picture */
            profile_picture?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Active */
            is_active: boolean;
        };
        /** UserTasteProfile */
        UserTasteProfile: {
            /** User Id */
            user_id: string;
            /**
             * Dietary Restrictions
             * @default []
             */
            dietary_restrictions: components["schemas"]["DietaryRestriction"][];
            /**
             * Cuisine Preferences
             * @default []
             */
            cuisine_preferences: components["schemas"]["CuisinePreference"][];
            flavor_profile?: components["schemas"]["FlavorProfile"] | null;
            /**
             * Liked Foods
             * @default []
             */
            liked_foods: components["schemas"]["FoodItem"][];
            /**
             * Disliked Foods
             * @default []
             */
            disliked_foods: components["schemas"]["FoodItem"][];
            /**
             * Favorite Restaurants
             * @default []
             */
            favorite_restaurants: string[];
            /** Price Range Preference */
            price_range_preference?: string | null;
            /**
             * Meal Time Preferences
             * @default {}
             */
            meal_time_preferences: {
                [key: string]: string[];
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VapiRequest */
        VapiRequest: {
            message: components["schemas"]["Message"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API welcome message and navigation links */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_auth_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthRequest"];
            };
        };
        responses: {
            /** @description Successful authentication */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *       "token_type": "bearer",
                     *       "user": {
                     *         "id": "uuid-string",
                     *         "email": "user@gmail.com",
                     *         "first_name": "John",
                     *         "last_name": "Doe",
                     *         "google_id": "google_user_123",
                     *         "profile_picture": "https://lh3.googleusercontent.com/...",
                     *         "created_at": "2024-01-01T00:00:00",
                     *         "is_active": true
                     *       },
                     *       "is_new_user": false
                     *     } */
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid Google ID token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Invalid Google ID token: Token verification failed"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User information retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "uuid-string",
                     *       "email": "user@gmail.com",
                     *       "first_name": "John",
                     *       "last_name": "Doe",
                     *       "google_id": "google_user_123",
                     *       "profile_picture": "https://lh3.googleusercontent.com/...",
                     *       "created_at": "2024-01-01T00:00:00",
                     *       "is_active": true
                     *     } */
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Could not validate credentials"
                     *     } */
                    "application/json": unknown;
                };
            };
        };
    };
    get_user_profile_user_profile__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Taste profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "profile": {
                     *         "user_id": "uuid-string",
                     *         "dietary_restrictions": [
                     *           "pescetarian",
                     *           "gluten-free"
                     *         ],
                     *         "cuisine_preferences": [
                     *           "italian",
                     *           "mexican",
                     *           "thai"
                     *         ],
                     *         "flavor_profile": "spicy",
                     *         "liked_foods": [
                     *           "pasta",
                     *           "tacos",
                     *           "pad thai"
                     *         ],
                     *         "disliked_foods": [
                     *           "mushrooms",
                     *           "olives"
                     *         ],
                     *         "favorite_restaurants": [
                     *           "restaurant_id_1",
                     *           "restaurant_id_2"
                     *         ],
                     *         "price_range_preference": "medium",
                     *         "meal_time_preferences": {
                     *           "breakfast": [
                     *             "light"
                     *           ],
                     *           "dinner": [
                     *             "hearty"
                     *           ]
                     *         },
                     *         "updated_at": "2024-01-01T00:00:00"
                     *       },
                     *       "recommendations_count": 15,
                     *       "last_activity": "2024-01-01T00:00:00"
                     *     } */
                    "application/json": components["schemas"]["TasteProfileResponse"];
                };
            };
            /** @description Access forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Not authorized to access this profile"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_profile_user_profile__user_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTasteProfile"];
            };
        };
        responses: {
            /** @description Profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "profile": {
                     *         "user_id": "uuid-string",
                     *         "dietary_restrictions": [
                     *           "vegetarian"
                     *         ],
                     *         "cuisine_preferences": [
                     *           "italian",
                     *           "mexican"
                     *         ],
                     *         "flavor_profile": "mild",
                     *         "liked_foods": [
                     *           "pasta",
                     *           "pizza"
                     *         ],
                     *         "disliked_foods": [
                     *           "mushrooms"
                     *         ],
                     *         "favorite_restaurants": [
                     *           "restaurant_id_1"
                     *         ],
                     *         "price_range_preference": "medium",
                     *         "meal_time_preferences": {
                     *           "lunch": [
                     *             "quick"
                     *           ]
                     *         },
                     *         "updated_at": "2024-01-01T12:00:00"
                     *       },
                     *       "recommendations_count": 8,
                     *       "last_activity": "2024-01-01T12:00:00"
                     *     } */
                    "application/json": components["schemas"]["TasteProfileResponse"];
                };
            };
            /** @description Access forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Not authorized to update this profile"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_profile_user_profile__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "Profile deleted successfully"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Access forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Not authorized to delete this profile"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Profile not found"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nearby_restaurants_restaurants_doordash_nearby_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NearbyRestaurantsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyRestaurantsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restaurant_menu_restaurants_doordash_restaurant__restaurant_id__menu_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantMenu"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restaurant_details_restaurants_doordash_restaurant__restaurant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Restaurant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restaurant_reviews_restaurants_google_maps_restaurant__restaurant_id__reviews_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantReviews"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_menu_item_reviews_restaurants_google_maps_restaurant__restaurant_id__item__item_name__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
                item_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItemReviews"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_place_details_restaurants_google_maps_restaurant__restaurant_id__place_details_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restaurant_top_items_restaurants_beli_restaurant__restaurant_id__top_items_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeliRestaurantTopItems"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_restaurants_beli_user__user_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeliUserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restaurants_restaurants__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of restaurants with basic information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_nearby_restaurants_restaurants__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NearbyRestaurantsRequest"];
            };
        };
        responses: {
            /** @description Restaurants found successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "restaurants": [
                     *         {
                     *           "id": "restaurant_123",
                     *           "name": "Tony's Pizza",
                     *           "address": "123 Main St, City, State",
                     *           "phone": "+1-555-0123",
                     *           "rating": 4.5,
                     *           "cuisine_tags": [
                     *             "italian",
                     *             "pizza"
                     *           ],
                     *           "image_url": "https://example.com/restaurant.jpg",
                     *           "distance_miles": 0.8
                     *         }
                     *       ],
                     *       "total_count": 25,
                     *       "search_radius_miles": 5
                     *     } */
                    "application/json": components["schemas"]["NearbyRestaurantsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restaurant_items_restaurants__restaurant_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restaurant data retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "id": "58134",
                     *       "name": "Giggling Rice Thai",
                     *       "average_rating": 4.7,
                     *       "menu_items": [],
                     *       "reviews": [],
                     *       "top_items": []
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Restaurant not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Restaurant not found"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendation_recs__restaurant_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description AI-generated food recommendation with reasoning and confidence score */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendation_context_recs__restaurant_id__context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary of user profile, restaurant data, and community insights */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_cart_vapi_item_cart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VapiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_to_cart_vapi_user_cart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VapiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restaurant_info_vapi_restaurant_by_id_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VapiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restaurant_list_vapi_restaurants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VapiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
